version: ~> 1.0 # needed for imports
import: scala/scala-dev:travis/default.yml

language: scala
scala:
  - 2.11.12
  - 2.12.8
  - 2.13.0
env:
  matrix:
    - ADOPTOPENJDK=8
    - ADOPTOPENJDK=11
services:
  - mysql
  - postgresql
  - docker
addons:
  postgresql: "9.4"
  apt:
    packages:
    - graphviz

before_install:
  # TZ needed for Oracle driver!
  - export TZ=Asia/Kamchatka
  - docker version

install:
  - sh -v travis/runcontainer.sh oracle db2
  - docker ps
  - sh -v ./travis/extractNonPublicDeps

script:
  - admin/build.sh
